local_costmap:
  global_frame: map
  robot_base_frame: chassis
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 20.0
  height: 20.0
  resolution: 0.05
